### ISSUE TITLE
开发模式中的no-console

### ISSUE THREAD

**Issue by xyxabcdiy** [sevenryze/towerflow#12]
在开发环境中，禁止 `console` 真的是一种很愚蠢的行为。

`console` 仍然是一种很重要的调试手段，使用起来会其他调试方法来的方便的多。

**Comment by sevenryze** [comment]
@xyxabcdiy 不对啊，我看了一下代码，web项目的设置，默认的警告级别是`warning`，开启了console.log只是警告而已啊。
